services:
  db:
    image: mysql:8.0
    container_name: demo-db-1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql/test.sql:/docker-entrypoint-initdb.d/test.sql
    # ----------------------
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.0-alpine
    container_name: demo-redis-1
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data

  app:
    build: .
    container_name: demo-app-1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test?characterEncoding=utf-8
    depends_on:
      db:
        condition: service_healthy